<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MacroElement extends \App\Entity\MacroElement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'edible_part', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'water', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'protein', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'lipids', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'carbohydrates', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'starch', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'soluble_sugars', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'fiber', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'food'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'edible_part', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'water', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'protein', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'lipids', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'carbohydrates', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'starch', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'soluble_sugars', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'fiber', '' . "\0" . 'App\\Entity\\MacroElement' . "\0" . 'food'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MacroElement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFood(): ?\App\Entity\Food
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFood', []);

        return parent::getFood();
    }

    /**
     * {@inheritDoc}
     */
    public function setFood(?\App\Entity\Food $food): \App\Entity\MacroElement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFood', [$food]);

        return parent::setFood($food);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEdiblePart(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdiblePart', []);

        return parent::getEdiblePart();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdiblePart(?string $edible_part): \App\Entity\MacroElement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdiblePart', [$edible_part]);

        return parent::setEdiblePart($edible_part);
    }

    /**
     * {@inheritDoc}
     */
    public function getWater(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWater', []);

        return parent::getWater();
    }

    /**
     * {@inheritDoc}
     */
    public function setWater(?string $water): \App\Entity\MacroElement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWater', [$water]);

        return parent::setWater($water);
    }

    /**
     * {@inheritDoc}
     */
    public function getProtein(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtein', []);

        return parent::getProtein();
    }

    /**
     * {@inheritDoc}
     */
    public function setProtein(?string $protein): \App\Entity\MacroElement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProtein', [$protein]);

        return parent::setProtein($protein);
    }

    /**
     * {@inheritDoc}
     */
    public function getLipids(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLipids', []);

        return parent::getLipids();
    }

    /**
     * {@inheritDoc}
     */
    public function setLipids(?string $lipids): \App\Entity\MacroElement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLipids', [$lipids]);

        return parent::setLipids($lipids);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarbohydrates(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarbohydrates', []);

        return parent::getCarbohydrates();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarbohydrates(?string $carbohydrates): \App\Entity\MacroElement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarbohydrates', [$carbohydrates]);

        return parent::setCarbohydrates($carbohydrates);
    }

    /**
     * {@inheritDoc}
     */
    public function getStarch(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStarch', []);

        return parent::getStarch();
    }

    /**
     * {@inheritDoc}
     */
    public function setStarch(?string $starch): \App\Entity\MacroElement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStarch', [$starch]);

        return parent::setStarch($starch);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolubleSugars(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolubleSugars', []);

        return parent::getSolubleSugars();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolubleSugars(?string $soluble_sugars): \App\Entity\MacroElement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolubleSugars', [$soluble_sugars]);

        return parent::setSolubleSugars($soluble_sugars);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiber', []);

        return parent::getFiber();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiber(?string $fiber): \App\Entity\MacroElement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiber', [$fiber]);

        return parent::setFiber($fiber);
    }

}
