<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM4giBW3\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM4giBW3/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerM4giBW3.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerM4giBW3\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerM4giBW3\App_KernelTestDebugContainer([
    'container.build_hash' => 'M4giBW3',
    'container.build_id' => 'cf7d6d36',
    'container.build_time' => 1685111982,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM4giBW3');
