<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_genid' => [['id'], ['_controller' => 'api_platform.action.not_exposed', '_api_respond' => 'true'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/.well-known/genid']], [], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '[^.]+', '_format' => 'jsonld'], [['variable', '.', 'jsonld', '_format', true], ['variable', '/', '[^.]+', 'shortName', true], ['text', '/api/contexts']], [], [], []],
    'app_analyses' => [[], ['_controller' => 'App\\Controller\\AnalysesController::index'], [], [['text', '/analyses']], [], [], []],
    'app_exercises' => [[], ['_controller' => 'App\\Controller\\ExercisesController::index'], [], [['text', '/exercises']], [], [], []],
    'app_expense' => [[], ['_controller' => 'App\\Controller\\ExpenseController::index'], [], [['text', '/expense']], [], [], []],
    'app_food' => [[], ['_controller' => 'App\\Controller\\FoodController::index'], [], [['text', '/food']], [], [], []],
    'language_switch' => [['_locale'], ['_locale' => 'en', '_controller' => 'App\\Controller\\LanguageController::switchLanguage'], [], [['variable', '/', '[^/]++', '_locale', true], ['text', '/language']], [], [], []],
    'meal' => [['_locale', 'name', 'type'], ['name' => null, 'type' => null, '_controller' => 'App\\Controller\\MealController::index'], [], [['variable', '/', '[^/]++', 'type', true], ['variable', '/', '[^/]++', 'name', true], ['text', '/meals/meal'], ['variable', '/', '[^/]++', '_locale', true]], [], [], []],
    'meal_listFoods' => [[], ['_controller' => 'App\\Controller\\MealController::listFoods'], [], [['text', '/MealController/listFoods']], [], [], []],
    'show' => [[], ['_controller' => 'App\\Controller\\MealController::show'], [], [['text', '/meals/show']], [], [], []],
    'salvaLista' => [[], ['_controller' => 'App\\Controller\\MealController::salvaLista'], [], [['text', '/meals/salvaLista']], [], [], []],
    'app_menu' => [[], ['_controller' => 'App\\Controller\\MenuController::index'], [], [['text', '/menu']], [], [], []],
    'app_recipe' => [[], ['_controller' => 'App\\Controller\\RecipeController::index'], [], [['text', '/recipe']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
