<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5jkcsBK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5jkcsBK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5jkcsBK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5jkcsBK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5jkcsBK\App_KernelDevDebugContainer([
    'container.build_hash' => '5jkcsBK',
    'container.build_id' => '8d6690d2',
    'container.build_time' => 1693725515,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5jkcsBK');
